ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 15
  AGENT_0:
    SENSORS: ['RGB_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
    ORIENTATION: [0, 0, 0]
TASK:
  TYPE: VLN-v0
  #SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR', 'INSTRUCTION_SENSOR']
  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass
  INSTRUCTION_SENSOR_UUID: instruction
  #MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'TOP_DOWN_MAP']
  SUCCESS:
    SUCCESS_DISTANCE: 3.0
DATASET:
  TYPE: R2RVLN-v1
  SPLIT: val_seen
  DATA_PATH: "data/datasets/vln/mp3d/r2r/v1/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"